### ISSUE TITLE
和MJRefresh一起用产生冲突

### ISSUE THREAD

**Issue by rainer-liao** [12207480/DOPDropDownMenu-Enhanced#12]
如图, 在使用MJRefresh的下拉刷新时, 如果MJRefresh的下拉刷新菊花还在转, 这个时候同时去点击DOPDropDownMenu, 会使整个DOPDropDownMenu下降某一高度. 

必现的事情

**Comment by 12207480** [comment]
没有图

**Comment by rainer-liao** [comment]
sorry,之前写错了, 是如题

**Comment by ryougizhou** [comment]
我的情况是tabBar的两个页面，其中一个用到了MJRefresh，点选一次dropDownMenu后从点击其他tabBar上另一个页面，再回来，整个tableView下降一个MJRefresh下拉刷新view的高度

**Comment by 12207480** [comment]
有截图吗

**Comment by ryougizhou** [comment]
http://www.cocoachina.com/bbs/read.php?tid=290961&page=6#1417330http://www.cocoachina.com/bbs/read.php?tid=290961&page=6#1417330

我在这里回复的，包括初步的解决办法，都在回复里面，应该是弹出下拉菜单的tableView时对原tableView层次有影响
