### ISSUE TITLE
双列菜单有异常

### ISSUE THREAD

**Issue by ShaneFang** [12207480/DOPDropDownMenu-Enhanced#13]
如题，如果有一个双列菜单，当leftTableView中的某个cell和rightTableView的某个cell相同时，点击左边cell，右边那个cell会默认选中。比如区县菜单，点选左边cell崇明，其中的右边cell崇明会默认选中。

**Comment by FisherFFFox** [comment]
![menu](https://cloud.githubusercontent.com/assets/12724076/9713657/73836064-5585-11e5-9d00-21d8d5355126.gif)

**Comment by 12207480** [comment]
已关注

**Comment by FisherFFFox** [comment]
能再问你一个问题么？怎么修改能做成下图这种同一column的多个row和item被同时选中的效果
![h30-c00_2015-09-15_10-38-33](https://cloud.githubusercontent.com/assets/12724076/9866598/b1b8ef86-5b96-11e5-8c6c-bf89933089b4.jpg)
