### ISSUE TITLE
能否更新个三角形可以换成自定义的图片

### ISSUE THREAD

**Issue by CaiNiaoXin** [12207480/DOPDropDownMenu-Enhanced#18]
大神能否更新个三角形可以换成自定义的图片，感谢

**Comment by hongdong** [comment]
也有同样的需求

**Comment by z563721** [comment]
你可以修改createIndicatorWithColor中返回的layer，在里面draw一个你自己的图片就可以了

**Comment by 12207480** [comment]
@property (nonatomic, strong) NSArray<NSString *> *indicatorImageNames;// 自定义指示器图片(在设置dataSource之前调用才会生效)
@property (nonatomic, strong) NSArray<NSNumber *> *indicatorAnimates;  // 指示器图片是否可以transform(在设置dataSource之前调用才会生效)
@property (nonatomic, assign) DOPIndicatorAlignType indicatorAlignType;
