### ISSUE TITLE
- (void)selectIndexPath:(DOPIndexPath *)indexPath;  方法失灵问题

### ISSUE THREAD

**Issue by liang-zhang** [12207480/DOPDropDownMenu-Enhanced#20]
我的代码如下：
    DOPIndexPath * indexPath = [DOPIndexPath indexPathWithCol:1 row:10 item:-1];
    [self.menu selectIndexPath:indexPath];
诡异的是：col设置为0 是正常的，但是别的都不好使

**Comment by songxin960757721** [comment]
我也遇到这样的问题，我的问题是，在设置数据源方法之后，调用这个方法，没效果， 一点反应也没有  self.menu.delegate = self;
    self.menu.dataSource = self;
    [self.menu selectIndexPath:[DOPIndexPath indexPathWithCol:0 row:6 item:6]];

**Comment by 12207480** [comment]
好的 我晚上看下

**Comment by 12207480** [comment]
fixed

**Comment by perter3077304** [comment]
我的也失灵了  我的就打不出来这个方法 默认值设置不了

**Comment by perter3077304** [comment]
[self.typeDop selectDefalutIndexPath];  用这个没用  二楼的那个我这边都打不出来
