### ISSUE TITLE
如何加到collectionview headerview 里面。事件失效了。

### ISSUE THREAD

**Issue by devyunji** [12207480/DOPDropDownMenu-Enhanced#24]
展开之后无法点击。

**Comment by zbjcool** [comment]
你好，我也遇到这个问题了，你找到原因了吗？

**Comment by devyunji** [comment]
@zbjcool 我已经解决了

**Comment by devyunji** [comment]
![image](https://cloud.githubusercontent.com/assets/16624762/13623059/a9161bc4-e5de-11e5-9701-8ab4262346f4.png)

menu = [[DOPDropDownMenu alloc] initWithOrigin:CGPointMake(0, (SCREEN_WIDTH*0.5)) andHeight:44.0];

关键代码:    [self.collectionView addSubview:menu];
