### ISSUE TITLE
我开始手动加入了DOPropDownMene,在用cocoapods 导入后报lonker错

### ISSUE THREAD

**Issue by liaodalin19903** [12207480/DOPDropDownMenu-Enhanced#26]
uplicate symbol _OBJC_IVAR_$_DOPDropDownMenu._numOfMenu in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_IVAR_$_DOPDropDownMenu._indicators in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_IVAR_$_DOPDropDownMenu._bgLayers in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_IVAR_$_DOPDropDownMenu._titles in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_IVAR_$_DOPDropDownMenu._textColor in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_IVAR_$_DOPDropDownMenu._separatorColor in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_IVAR_$_DOPDropDownMenu._indicatorColor in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_IVAR_$_DOPIndexPath._column in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_IVAR_$_DOPDropDownMenu._origin in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_CLASS_$_DOPIndexPath in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_METACLASS_$_DOPIndexPath in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_IVAR_$_DOPDropDownMenu._delegate in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
duplicate symbol _OBJC_IVAR_$_DOPDropDownMenu._dataSource in:
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Intermediates/agriculturalApp.build/Debug-iphonesimulator/agriculturalApp.build/Objects-normal/x86_64/DOPDropDownMenu.o
    /Users/youpude/Library/Developer/Xcode/DerivedData/agriculturalApp-ebtktqjqltyjeegekhyqrvkfgmhp/Build/Products/Debug-iphonesimulator/libDOPDropDownMenu-Enhanced.a(DOPDropDownMenu.o)
ld: 20 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by 12207480** [comment]
重复导入了 查看项目中是否 本来就有 或者 查看build phase 搜索 DOPDropDownMenu

**Comment by liaodalin19903** [comment]
之前有倒入DOPDropDownMenu，现在倒入enhanced 会出现这个情况


发自我的 iPhone

**Comment by 12207480** [comment]
build phase 删除 之前的
