### ISSUE TITLE
关于选择后原始layer没有移除的问题

### ISSUE THREAD

**Issue by z563721** [12207480/DOPDropDownMenu-Enhanced#45]
我这里手动把bglayer的颜色跟self.backgourndColor挂钩，原来是准备把背后的东西显示出来，
然而发现，当选择tableview的任何一个row之后
textLayer确实更新了，但是旧的文字却没有移除掉

**Comment by 12207480** [comment]
这是个bug，可是我没时间改

**Comment by z563721** [comment]
#46
