### ISSUE TITLE
最上面底部的线不显示

### ISSUE THREAD

**Issue by jianjianhao** [12207480/DOPDropDownMenu-Enhanced#49]
![simulator screen shot 2017 7 18 9 55 56](https://user-images.githubusercontent.com/12797357/28297300-bc47801e-6b9f-11e7-8070-202e8b48fad4.png)

**Comment by bluesky0109** [comment]
fe18734ad50 提交已修改该问题，需要维护者 更新pods，或者您自己clone最新代码
