### ISSUE TITLE
直接点击重新加载crash，xcode环境7.2.1，iOS 系统版本8.3

### ISSUE THREAD

**Issue by Brances** [12207480/DOPDropDownMenu-Enhanced#59]
![image](https://user-images.githubusercontent.com/10275640/31326978-84fba9e0-ac91-11e7-8302-7244d1054333.png)

![image](https://user-images.githubusercontent.com/10275640/31326994-a3430be6-ac91-11e7-9da7-991cef794572.png)

**Comment by Brances** [comment]
麻烦有时间看一下~

**Comment by 12207480** [comment]
好的

**Comment by 12207480** [comment]
已经修复

**Comment by Brances** [comment]
在数据源的方法中已经找到，谢谢~

**Comment by bluesky0109** [comment]
@12207480   修复的issue能抽时间整理 关闭下吗
