### ISSUE TITLE
当数据源只有一组时 小箭头离 标题太远了

### ISSUE THREAD

**Issue by bluesky0109** [12207480/DOPDropDownMenu-Enhanced#8]
![2907f113-845f-4a44-a9cd-8430312d7f46](https://cloud.githubusercontent.com/assets/8929364/8175175/da600458-1418-11e5-8fb7-6827587f8d8a.png)

**Comment by 12207480** [comment]
你是需要箭头跟随标题吗

**Comment by bluesky0109** [comment]
嗯，一般应该是箭头 跟随标题吧，跟标题之间有点距离就行了，目前的只有一组时箭头偏离太远了些吧

**Comment by cherishloveyou** [comment]
这个箭头和标题这块里面我看了下  实现得不是很好 修改比较繁琐

**Comment by cheng77** [comment]
你可以修改这段代码中的Position对应小箭头的x的坐标，改下间距就可以了
CAShapeLayer *indicator = [self createIndicatorWithColor:self.indicatorColor andPosition:CGPointMake((i + 1)*separatorLineInterval - 10, self.frame.size.height / 2)];

我的是2列   CAShapeLayer *indicator = [self createIndicatorWithColor:self.indicatorColor andPosition:CGPointMake((i + 1)*separatorLineInterval - 55, self.frame.size.height/2+2.5)];
暂时这样改 看着美观点！
